### ISSUE TITLE
Expected a 'cuda' device type for generator but found 'cpu'

### ISSUE THREAD

**Issue by JonnesLin** [lywang3081/AFEC#4] opened 2022-10-29 07:03 UTC
Hi,

When I ran the following command: python ./main.py --dataset CUB200 --trainer ewc --lamb 40 --lamb_emp 0.001, an error happened: Expected a 'cuda' device type for generator but found 'cpu'

Could you help me to figure it out? Thank you very much!

**Comment by lywang3081** [comment] 2022-10-29 07:34
Hi, could you show more details about this bug?

BTW, from my experience, it is possibly caused by the cuda version and might be addressed by replacing "kwargs = {'num_workers': 8, 'pin_memory': True}" into "kwargs = {'num_workers': 0, 'pin_memory': False}" in main.py line 123 and afec_ewc.py line 93.

**Comment by JonnesLin** [comment] 2022-10-29 17:54
ahhh that works for me. Thank u!

**Comment by JonnesLin** [comment] 2022-10-29 19:22
Ahhhh it doesn't work

**Comment by lywang3081** [comment] 2022-11-02 10:39
Could you provide more details about it?

**Closed as completed** 2022-11-12 13:20 UTC
